export const ADD_ONE = 'ADD_ONE'
export const MINUS_ONE = 'MINUS_ONE'
export const CHANGE_NAME = 'CHANGE_NAME'
export const CHANGE_COLOR = 'CHANGE_COLOR'
export const SELECT_BOOK = 'SELECT_BOOK'
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES'
export const CHANGE_FONTSIZE = 'CHANGE_FONTSIZE'
export const CHANGE_MODE = 'CHANGE_MODE'
